# Generated by Django 3.1.2 on 2020-11-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201105_0528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='person',
            new_name='user',
        ),
    ]
